---
- name: get osp facts
  gather_facts: false
  hosts: jumpbox
  roles:
    - osp-facts
    
- name: deploy haproxy
  hosts: frontends
  # gather_facts: false # remove later! speeds up testing
  become: true
  roles:
    - configuration
    - haproxy 

- name: deploy postgres
  #gather_facts: false
  become: true
  hosts: appdbs
  roles:
    - configuration
    - geerlingguy.postgresql

- name: deploy apache
  #gather_facts: false
  become: true
  hosts: apps
  roles:
    - configuration
    - tomcat

